### ISSUE TITLE
Project is not open source without a license file

### ISSUE THREAD

**Issue by karan** [USG-SCOPE/data-dictionary#1]
Without a license, this project isn't open source and no one can use the code.

Please use something like http://choosealicense.com/ to decide what license to use. I recommend MIT or GPL.

**Comment by peterbenmeyer** [comment]
Thank you.  I'll research.  We have no code here yet but it will come up.

**Comment by kulnor** [comment]
Is this is just documentation, I would suggest a Creative Commons license. Otherwise for code would strongly encourage highly permissive license such as MIT, Apache2, BSD, and the likes to maximize adoption.

**Comment by peterbenmeyer** [comment]
Most authors are U.S. government staff.  Probably we want it to be public domain, which is the usual legal category for U.S. government staff works.  It would be good and kind for others to cite our work if it is useful.  When I looked at choosealicense.com I didn't see a clear instruction for our situation so I am holding off on a bit.  Will need a consensus among my work group.

**Comment by akuckartz** [comment]
This might be an option:

CC0 1.0 Universal (CC0 1.0)
Public Domain Dedication
https://creativecommons.org/publicdomain/zero/1.0/

**Comment by peterbenmeyer** [comment]
Done and closed.  I imitated what the CFPB agency does, in a simplified way.  Now there is a [TERMS.md](https://github.com/USG-SCOPE/data-dictionary/blob/gh-pages/TERMS.md) that says it's available as CC0 1.0 Universal Public Domain, as suggested by akuckartz and implemented by CFPB.  Also [README.md ](https://github.com/USG-SCOPE/data-dictionary/blob/gh-pages/README.md)now guides users looking for license info to the TERMS.md. Feel free to advise us further on this point.

**Comment by peterbenmeyer** [comment]
Done and closed.  Feel free to advise us further on this point.
